Rokomari/CWO/urls.py
from django.urls import path
from . import views

app_name = "CWO"
urlpatterns = [
    path('cart/', views.cart, name='cart'),
    path('wishlist/', views.wishlist, name='wishlist'),
    path('order/', views.order, name='order'),
    path('order/<int:order_id>/', views.specific_order, name='specific_order'),
    path('allOrder/', views.all_order, name='all_order'),
    path('cart/<str:product_id>/', views.delete_cart_item, name='delete_cart_item'),
    path('wishlist/<str:product_id>/', views.delete_wishlist_item, name='delete_wishlist_item'),
    path('addc/<str:product_id>/', views.add_to_cart, name='add_to_cart'),
    path('addw/<str:product_id>/', views.add_to_wishlist, name='add_to_wishlist'),
    path('update_cart/<str:product_id>/', views.update_cart, name='update_cart'),
    path('addc1/<str:product_id>/', views.add_to_cart_from_wishlist, name='add_to_cart_from_wishlist'),
]

Rokomari/RC/urls.py
from django.urls import path, include
from . import views

app_name = "RC"
urlpatterns = [
    path('giveRating/<str:product_id>', views.give_rating, name='give_rating'),
    path('addComment/<str:product_id>', views.add_comment, name='add_comment')
]

Rokomari/Rokomari/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('', include('search_query.urls'))
]

Rokomari/home/urls.py
from django.urls import path, include
from . import views

app_name = "home"
urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('user-profile', views.user_profile, name='user_profile'),
    path('admin', views.admin_login, name='admin_login'),
    path('admindashboard/', views.admin, name='admin'),
    path('add-electronics', views.add_electronics, name='add_electronics'),
    path('update-electronics', views.update_electronics, name='update_electronics'),
    path('add-brand', views.add_brand, name='add_brand'),
    path('add-electronics-category', views.add_electronics_category, name='add_electronics_category'),
    path('add-book' , views.add_book , name='add_book'),
    path('add-book-category' , views.add_book_category , name = 'add_book_category'),
    path('all-books' , views.all_books , name='all_books'),
    path('all-electronics' , views.all_electronics , name = 'all_electronics'),
    path('all-orders' , views.all_orders , name = 'all_orders'),
    path('add-author' , views.add_author , name = 'add_author'),
    path('add-publisher' , views.add_publisher , name = 'add_publisher'),
    path('', include('books.urls')),
    path('', include('electronics.urls')),
    path('', include('CWO.urls')),
    path('', include('RC.urls')),
    path('', include('search_query.urls'))
]

Rokomari/CWO/views.py
from django.shortcuts import render
from miscellaneous.miscellaneous import *
from django.shortcuts import redirect
import cx_Oracle


# Create your views here.
#Cart Start


def cart(request):

    dict = {}
    dict['username'] = request.session.get('username')
    dict['id'] = request.session.get('id')
    dict['mobile'] = request.session.get('mobile')
    dict['email'] = request.session.get('email')
    dict['address'] = request.session.get('address')
    dict['account_type'] = request.session.get('account_type')
    dict['password'] = request.session.get('password')
    dict['login_message'] = request.session.get('login_message')
    dict['cart_size'] = get_book_cart_len( dict['id'], 1) + get_electronics_cart_len(dict['id'], 1)
    dict['wishlist_size'] = get_book_wishlist_len(dict['id']) + get_electronics_wishlist_len(dict['id'])


    res = get_book_cart(request.session.get('id'))
    lst = []
    for item in res:
        """
        a, b, c = get_product_name_price(item['BOOK ID'])
        d = item['BOOK QUANTITY']
        """
        a, b, c, d = item['BOOK ID'], item['TITLE'], item['PRICE'], item['BOOK QUANTITY']
        lst.append((a, b, c, d))
    res = get_electronics_cart(request.session.get('id'))
    for item in res:
        """
        a, b, c = get_product_name_price(item['ELECTRONICS ID'])
        d = item['ELECTRONICS QUANTITY']
        """
        a, b, c, d = item['ELECTRONICS ID'], item['TITLE'], item['PRICE'], item['ELECTRONICS QUANTITY']
        lst.append((a, b, c, d))
    dict['cart'] = lst


    print(dict['cart'])
    total = 0
    for a, b, c, d in dict['cart']:
        total += int(c)
    dict['total'] = total

    return render(request, 'CWO/cart.html', dict)


def add_to_cart(request, product_id):
    dsn_tns = cx_Oracle.makedsn('localhost', '1521', service_name='ORCLPDB')
    conn = cx_Oracle.connect(user='MYSELF', password='123', dsn=dsn_tns)
    cursor = conn.cursor()
    quantity = 1
    order_id = 1
    id = int(max_cart_id(product_id)) + 1
    customer_id = request.session.get('id')
    if int(product_id) < THRESHOLD:
        """
        cursor.execute('''SELECT * FROM "MYSELF"."BOOK CART" WHERE "BOOK ID" =: product_id AND "USER ID" =: customer_id 
                        AND "ORDER ID" =: order_id''', { 'product_id' : product_id, 'customer_id' : customer_id, 'order_id' : order_id})
        res = dict_fetch_all(cursor)
        if len(res) == 0:
            cursor.execute('''
                                INSERT INTO "MYSELF"."BOOK CART"("ID", "USER ID", "BOOK ID", "BOOK QUANTITY", "ORDER ID")
                                VALUES( :id, :customer_id, :product_id, :quantity, :order_id)
                                ''', [id, customer_id, product_id, quantity, order_id])
        """
        print(id, end=' ')
        print(customer_id, end=' ')
        print(product_id, end=' ')
        print(order_id, end=' ')
        print(quantity)
        cursor.callproc('ADD_TO_BOOK_CART', [id, customer_id, product_id, order_id, quantity])
    else:
        """
        cursor.execute('''SELECT * FROM "MYSELF"."ELECTRONICS CART" WHERE "ELECTRONICS ID" =: product_id AND "USER ID" =: customer_id 
                                AND "ORDER ID" =: order_id''',
                       {'product_id': product_id, 'customer_id': customer_id, 'order_id': order_id})
        res = dict_fetch_all(cursor)
        if len(res) == 0:
            cursor.execute('''
                                        INSERT INTO "MYSELF"."ELECTRONICS CART"("ID", "USER ID", "ELECTRONICS ID", "ELECTRONICS QUANTITY", "ORDER ID")
                                        VALUES( :id, :customer_id, :product_id, :quantity, :order_id)
                                        ''', [id, customer_id, product_id, quantity, order_id])
        """
        cursor.callproc('ADD_TO_ELECTRONICS_CART', [id, customer_id, product_id, order_id, quantity])
    conn.commit()
    conn.close()
    if int(product_id) < THRESHOLD:
        return redirect('home:books:book_details', book_id=product_id)
    else:
        return redirect('home:electronics:electronics_details', electronics_id=product_id)


def delete_cart_item(request, product_id):
    customer_id = request.session.get('id')
    print(product_id + " " + str(customer_id))
    dsn_tns = cx_Oracle.makedsn('localhost', '1521', service_name='ORCLPDB')
    conn = cx_Oracle.connect(user='MYSELF', password='123', dsn=dsn_tns)
    cursor = conn.cursor()
    order_id = 1
    if int(product_id) < THRESHOLD:
        cursor.execute('''DELETE FROM "MYSELF"."BOOK CART" WHERE "BOOK ID" =:product_id AND "USER ID" =:customer_id AND "ORDER ID" =: order_id
                        ''', {'product_id': product_id, 'customer_id': customer_id, 'order_id': order_id})
    else:
        cursor.execute('''DELETE FROM "MYSELF"."ELECTRONICS CART" WHERE "ELECTRONICS ID" =:product_id AND "USER ID" =:customer_id AND "ORDER ID" =: order_id
                                ''', {'product_id': product_id, 'customer_id': customer_id, 'order_id': order_id})
    conn.commit()
    conn.close()
    return redirect('/cart/')

def update_cart(request, product_id):
    dsn_tns = cx_Oracle.makedsn('localhost', '1521', service_name='ORCLPDB')
    conn = cx_Oracle.connect(user='MYSELF', password='123', dsn=dsn_tns)
    cursor = conn.cursor()
    customer_id = request.session.get('id')
    quantity = request.GET.get(product_id)
    if int(product_id) < THRESHOLD:
        cursor.execute('''UPDATE "MYSELF"."BOOK CART" SET "BOOK QUANTITY" := quantity WHERE "BOOK ID" =: product_id AND "USER ID" =: customer_id AND "ORDER ID" =: order_id
                        ''', {'quantity': quantity, 'product_id':product_id, 'customer_id':customer_id, 'order_id': 1})
    else:
        cursor.execute('''UPDATE "MYSELF"."ELECTRONICS CART" SET "ELECTRONICS QUANTITY" := quantity WHERE "ELECTRONICS ID" =: product_id AND "USER ID" =: customer_id AND "ORDER ID" =: order_id
                                ''',
                       {'quantity': quantity, 'product_id': product_id, 'customer_id': customer_id, 'order_id': 1})
    conn.commit()
    cursor.close()
    conn.close()
    return redirect('/cart/')

#Cart End


#Wishlist Start


def wishlist(request):

    dict = {}
    dict['username'] = request.session.get('username')
    dict['id'] = request.session.get('id')
    dict['mobile'] = request.session.get('mobile')
    dict['email'] = request.session.get('email')
    dict['address'] = request.session.get('address')
    dict['account_type'] = request.session.get('account_type')
    dict['password'] = request.session.get('password')
    dict['login_message'] = request.session.get('login_message')
    dict['cart_size'] = get_book_cart_len(dict['id'], 1) + get_electronics_cart_len(dict['id'], 1)
    dict['wishlist_size'] = get_book_wishlist_len(dict['id']) + get_electronics_wishlist_len(dict['id'])

    res = get_book_wishlist(dict['id'])
    lst = []
    for item in res:
        """
        lst.append(get_product_name_price(item['BOOK ID']))
        """
        lst.append((item['BOOK ID'], item['TITLE'], item['PRICE']))
    res = get_electronics_wishlist(dict['id'])
    for item in res:
        lst.append((item['ELECTRONICS ID'], item['TITLE'], item['PRICE']))
    dict['wishlist'] = lst

    print(dict['wishlist'])


    return render(request, 'CWO/wishlist.html', dict)


def add_to_wishlist(request, product_id):
    dsn_tns = cx_Oracle.makedsn('localhost', '1521', service_name='ORCLPDB')
    conn = cx_Oracle.connect(user='MYSELF', password='123', dsn=dsn_tns)
    cursor = conn.cursor()
    customer_id = request.session.get('id')
    id = int(max_wishlist_id(product_id)) + 1;
    if int(product_id) < THRESHOLD:
        cursor.execute('''SELECT * FROM "MYSELF"."BOOK WISHLIST" WHERE "BOOK ID" =: product_id AND "USER ID" =: customer_id 
                        ''',
                       {'product_id': product_id, 'customer_id': customer_id})
        res = dict_fetch_all(cursor)
        if len(res) == 0:
            cursor.execute('''
                                INSERT INTO "MYSELF"."BOOK WISHLIST"("ID", "USER ID", "BOOK ID")
                                VALUES( :id, :customer_id, :product_id)
                                ''', [id, customer_id, product_id])
    else:
        cursor.execute('''SELECT * FROM "MYSELF"."ELECTRONICS WISHLIST" WHERE "ELECTRONICS ID" =: product_id AND "USER ID" =: customer_id 
                                ''',
                       {'product_id': product_id, 'customer_id': customer_id})
        res = dict_fetch_all(cursor)
        if len(res) == 0:
            cursor.execute('''
                                        INSERT INTO "MYSELF"."ELECTRONICS WISHLIST"("ID", "USER ID", "ELECTRONICS ID")
                                        VALUES( :id, :customer_id, :product_id)
                                        ''', [id, customer_id, product_id])
    conn.commit()
    conn.close()
    if int(product_id) < THRESHOLD:
        return redirect('home:books:book_details', book_id=product_id)
    else:
        return redirect('home:electronics:electronics_details', electronics_id=product_id)


def add_to_cart_from_wishlist(request, product_id):
    dsn_tns = cx_Oracle.makedsn('localhost', '1521', service_name='ORCLPDB')
    conn = cx_Oracle.connect(user='MYSELF', password='123', dsn=dsn_tns)
    cursor = conn.cursor()
    quantity = 1
    order_id = 1
    id = int(max_cart_id(product_id)) + 1;
    customer_id = request.session.get('id')
    if int(product_id) < THRESHOLD:
        cursor.execute('''SELECT * FROM "MYSELF"."BOOK CART" WHERE "BOOK ID" =: product_id AND "USER ID" =: customer_id 
                            AND "ORDER ID" =: order_id''',
                       {'product_id': product_id, 'customer_id': customer_id, 'order_id': order_id})
        res = dict_fetch_all(cursor)
        if len(res) == 0:
            cursor.execute('''

Rokomari/templates/CWO/allOrders.html
{% extends "home/home.html" %}
{% load static %}

    {% block sliding_block %}
    {% endblock %}
    {% block body_block%}
    <link rel="stylesheet" href="{% static "books/css/style.css" %}">
        <div class="featured-product product">
            <div class="container-fluid">
                <div class="section-header">
                    <h1>Order History</h1>
                </div>
            </div>
        </div>

        {% if allOrderItems %}
            {% for items in allOrderItems %}
           <div class="featured-product product">
            <div class="container-fluid">
                <div class="section-header">
                    <h2><a href={% url 'home:CWO:specific_order' items.order_id %}> Order No: {{ items.order_id }}</a></h2>
            <div class="table-responsive">
            <table class="table table-bordered">
            <thead class="thead-dark">
            <tr>
                <th>Title</th>
                <th>Price</th>
                <th>Quantity</th>
            </tr>
            </thead>
            <tbody>
            {% for id, title, price, quantity in items.lst %}
                <tr>
                    <td>{{ title }}</td>
                    <td>{{ price }}</td>
                    <td>{{ quantity }}</td>
                </tr>
            {% endfor %}
                <tr>
                    <td>Total</td>
                    <td>{{ items.total }}</td>
                </tr>
            </tbody>
            </table>
            </div>
            <div class="price">
                <h4>Status : {{ items.status }}</h4>
            </div>
                </div>
            </div>
        </div>
            {% endfor %}
        {% elif not allOrderIDs %}
            <div class="featured-product product">
                    <div class="container-fluid">
                         <div class="section-header">
                            <p>Nothing is ordered</p>
                         </div>
                     </div>
            </div>
        {% endif %}
            <br>
            <br>

    {% endblock %}

    {% block best_seller  %}

    {% endblock %}

Rokomari/templates/CWO/cart.html
{% extends "home/home.html" %}
{% load static %}

    {% block sliding_block %}
    {% endblock %}
    {% block body_block%}

    <link rel="stylesheet" href="{% static "books/css/style.css" %}">
        <div class="featured-product product">
            <div class="container-fluid">
                <div class="section-header">
                    <h1>CART</h1>
                </div>
            </div>
        </div>
        {% if cart %}
            <div class="featured-product product">
            <div class="container-fluid">
                <div class="section-header">
                <div class="table-responsive">
            <form action="{% url 'home:CWO:order' %}" method = 'get'>
            <table class="table table-bordered">
            <thead class="thead-dark">
            <tr>
                <th>Title</th>
                <th>Price</th>
                <th>Quantity</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for  id, title, price, quantity in cart %}
                <tr>
                    <td>{{ title }}</td>
                    <td>{{ price }}</td>
                    <td><input type="number" value=1 min=1 name = {{ id }} ></td>
                    <td><a class="btn" href={% url 'home:CWO:delete_cart_item' id%}> Remove From Cart </a> </td>
                </tr>
            {% endfor %}
            </tbody>
            </table>
            <br><input class="btn btn-primary" type="submit" value="Order"/>
            </form>
                </div>
            </div>
            </div>
            </div>
        {% elif not cart %}
            <div class="featured-product product">
                    <div class="container-fluid">
                         <div class="section-header">
                            <p>Cart is empty</p>
                         </div>
                     </div>
            </div>
        {% endif %}
        <br>
        <br>
    {% endblock %}

    {% block best_seller  %}

    {% endblock %}

Rokomari/templates/CWO/specificOrder.html
{% extends "home/home.html" %}
{% load static %}

     {% block sliding_block %}
    {% endblock %}
    {% block body_block%}

    <link rel="stylesheet" href="{% static "books/css/style.css" %}">
         <div class="featured-product product">
            <div class="container-fluid">
                <div class="section-header">
                    <h1>Order No: {{ order_id }}</h1>
                </div>
            </div>
        </div>
        {% if specificOrder %}
            <div class="featured-product product">
            <div class="container-fluid">
                <div class="section-header">
                <div class="table-responsive">
            <table class="table table-bordered">
            <thead class="thead-dark">
            <tr>
                <th>Title</th>
                <th>Price</th>
                <th>Quantity</th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for id, title, price, quantity in specificOrder %}
                <tr>
                    <td>{{ title }}</td>
                    <td>{{ price }}</td>
                    <td>{{ quantity }}</td>
                </tr>
            {% endfor %}
                <tr>
                    <td>Total</td>
                    <td>{{ total }}</td>
                </tr>
            </tbody>
            </table>
                </div>

            <div class="price">
                <h4>Status : {{ status }}</h4>
            </div>
        {% elif not specificOrder %}
            <p>Nothing is Ordered</p>
        {% endif %}
        <br>
        <br>
        <h2><a href={% url 'home:home' %}>Return to Homepage </a></h2>
        <br>
        <br>
        </div>
        </div>
        </div>
    {% endblock %}

    {% block best_seller  %}

    {% endblock %}

Rokomari/templates/CWO/wishlist.html
{% extends "home/home.html" %}
{% load static %}

    {% block sliding_block %}
    {% endblock %}
    {% block body_block%}

    <link rel="stylesheet" href="{% static "books/css/style.css" %}">
       <div class="featured-product product">
            <div class="container-fluid">
                <div class="section-header">
                    <h1>WISH LIST</h1>
                </div>
            </div>
        </div>
        {% if wishlist %}
            <div class="featured-product product">
            <div class="container-fluid">
                <div class="section-header">
            <div class="table-responsive">
            <table class="table table-bordered">
            <thead class="thead-dark">
            <tr>
                <th>Title</th>
                <th>Price</th>
                <th></th>
                <th></th>
            </tr>
            </thead>
            <tbody>
            {% for id, title, price in wishlist %}
                <tr>
                    <td>{{ title }}</td>
                    <td>{{ price }}</td>
                    <td><a class="btn" href={% url 'home:CWO:delete_wishlist_item' id%}> Remove From Wishlist </a> </td>
                    <td><a class="btn" href={% url 'home:CWO:add_to_cart_from_wishlist' id%}> Add To Cart </a> </td>
                </tr>
            {% endfor %}
            </tbody>
            </table>
            </div>
                </div>
            </div>
            </div>
        {% elif not wishlist %}
            <div class="featured-product product">
                    <div class="container-fluid">
                         <div class="section-header">
                            <p>Wish List is empty</p>
                         </div>
                     </div>
            </div>
        {% endif %}
        <br>
        <br>
    {% endblock %}

    {% block best_seller  %}

    {% endblock %}