Rokomari/RC/urls.py
from django.urls import path, include
from . import views

app_name = "RC"
urlpatterns = [
    path('giveRating/<str:product_id>', views.give_rating, name='give_rating'),
    path('addComment/<str:product_id>', views.add_comment, name='add_comment')
]

Rokomari/Rokomari/urls.py
from django.urls import path, include

urlpatterns = [
    path('', include('home.urls')),
    path('', include('search_query.urls'))
]

Rokomari/home/urls.py
from django.urls import path, include
from . import views

app_name = "home"
urlpatterns = [
    path('', views.index, name='index'),
    path('home/', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('user-profile', views.user_profile, name='user_profile'),
    path('admin', views.admin_login, name='admin_login'),
    path('admindashboard/', views.admin, name='admin'),
    path('add-electronics', views.add_electronics, name='add_electronics'),
    path('update-electronics', views.update_electronics, name='update_electronics'),
    path('add-brand', views.add_brand, name='add_brand'),
    path('add-electronics-category', views.add_electronics_category, name='add_electronics_category'),
    path('add-book' , views.add_book , name='add_book'),
    path('add-book-category' , views.add_book_category , name = 'add_book_category'),
    path('all-books' , views.all_books , name='all_books'),
    path('all-electronics' , views.all_electronics , name = 'all_electronics'),
    path('all-orders' , views.all_orders , name = 'all_orders'),
    path('add-author' , views.add_author , name = 'add_author'),
    path('add-publisher' , views.add_publisher , name = 'add_publisher'),
    path('', include('books.urls')),
    path('', include('electronics.urls')),
    path('', include('CWO.urls')),
    path('', include('RC.urls')),
    path('', include('search_query.urls'))
]

Rokomari/home/views.py
from django.shortcuts import render
from .forms import *
from miscellaneous.miscellaneous import *
from django.shortcuts import redirect
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import reverse

# Create your views here.
def index(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            if authenticate(username, password):
                all_customers = all_users()
                dict = get_current_customer(all_customers, username)
                print(username)
                request.session['username'] = dict['NAME']
                request.session['id'] = dict['ID']
                request.session['mobile'] = dict['PHONE NUMBER']
                request.session['email'] = dict['EMAIL']
                request.session['address'] = dict['ADDRESS']
                #request.session['password'] = dict['PASSWORD']
                request.session['account_type'] = dict['TYPES']
                request.session['login_message'] = "Login Successful! Welcome, "+dict['NAME']
                return redirect('/home/')
            else:
                form = LoginForm()
                dict = {}
                dict['login_message'] = "Login Failed! Sorry"
                dict['form'] = form
                return render(request, 'home/index.html', dict)
    else:
        request.session.flush()
        form = LoginForm()
        return render(request, 'home/index.html', {'form': form})

def home(request):
    if 'username' in request.session:
        dict={}
        dict['username'] = request.session.get('username')
        dict['id'] = request.session.get('id')
        dict['mobile'] = request.session.get('mobile')
        dict['email'] = request.session.get('email')
        dict['address'] = request.session.get('address')
        dict['account_type'] = request.session.get('account_type')
        dict['password'] = request.session.get('password')
        dict['login_message'] = request.session.get('login_message')
        dict['cart_size'] = len(get_book_cart(request.session.get('id'))) + len(get_electronics_cart(request.session.get('id')))
        dict['wishlist_size'] = len(get_book_wishlist(request.session.get('id'))) + len(get_electronics_wishlist(request.session.get('id')))
        dict['bestseller'] = bestseller()
        return render(request, 'home/home.html', dict)
    else:
        form = LoginForm()
        return render(request, 'home/index.html', {'form': form})

def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            mobile = form.cleaned_data['mobile']
            address = form.cleaned_data['address']
            if check_username(username):
                form = UserForm()
                request.session['login_message'] = 'Duplicate Name, Please try another'
                return render(request, 'home/signup.html', {'form': form})
            if check_email(email):
                form = UserForm()
                request.session['login_message'] = 'Duplicate Email, Please try another'
                return render(request, 'home/signup.html', {'form': form})
            id = int(max_customer_id())
            id = id + 1
            print("******")
            print(id)
            create_customer(id, username, email, mobile, address, password, 'C')
            all_customers = all_users()
            dict = get_current_customer(all_customers, username)
            request.session['username'] = dict['NAME']
            request.session['id'] = dict["ID"]
            request.session['mobile'] = dict['PHONE NUMBER']
            request.session['email'] = dict['EMAIL']
            request.session['address'] = dict['ADDRESS']
            #request.session['password'] = dict['PASSWORD']
            request.session['account_type'] = dict['TYPES']
            request.session['login_message'] = "Congratulations " + dict['NAME'] + ", Sign Up Successful"
            return redirect('/home/')
    else:
        form = UserForm()
    return render(request, 'home/signup.html', {'form': form})

def user_profile(request):
    if request.method == "POST":
        form = UserProfileForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            email = form.cleaned_data['email']
            mobile = form.cleaned_data['mobile']
            address = form.cleaned_data['address']
            id = request.session.get('id')  #"getting current customer's id"

            update_customer(id, username, email, mobile, address, password)
            all_customers = all_users()
            dict = get_current_customer(all_customers, username)
            request.session['username'] = dict['NAME']
            request.session['id'] = dict["ID"]
            request.session['mobile'] = dict['PHONE NUMBER']
            request.session['email'] = dict['EMAIL']
            request.session['address'] = dict['ADDRESS']
            request.session['password'] = password
            request.session['account_type'] = dict['TYPES']

            form = UserProfileForm()
            form.fields['username'].initial = dict['NAME']
            form.fields['password'].initial = '*'*len(password)
            form.fields['email'].initial = dict['EMAIL']
            form.fields['mobile'].initial = dict['PHONE NUMBER']
            form.fields['account_type'].initial = dict['TYPES']
            form.fields['address'].initial = dict['ADDRESS']

            s = {'username': dict['NAME'], 'mobile': dict['PHONE NUMBER'], 'email': dict['EMAIL'], 'address': dict['ADDRESS'],
                 'account_type': dict['TYPES'], 'password': password, 'form': form,
                 'cart_size': len(get_book_cart(request.session.get('id'))) + len(get_electronics_cart(request.session.get('id'))),
                 'wishlist_size' : len(get_book_wishlist(request.session.get('id'))) + len(get_electronics_wishlist(request.session.get('id')))}

            s['all_orders'] = get_orders_of_this_user(dict["ID"])

            return render(request, 'home/user_profile.html', s)
    elif 'username' in request.session:
        dict = {'username': request.session.get('username'), 'id': request.session.get('id'),
                'mobile': request.session.get('mobile'), 'email': request.session.get('email'),
                'address': request.session.get('address'), 'account_type': request.session.get('account_type'),
                'password': request.session.get('password'), 'cart_size': len(get_book_cart(request.session.get('id'))) + len(get_electronics_cart(request.session.get('id'))),
                'wishlist_size' : len(get_book_wishlist(request.session.get('id'))) + len(get_electronics_wishlist(request.session.get('id')))}
        form = UserProfileForm()
        form.fields['username'].initial = dict['username']
        form.fields['password'].initial = dict['password']
        form.fields['email'].initial = dict['email']
        form.fields['mobile'].initial = dict['mobile']
        form.fields['account_type'].initial = dict['account_type']
        form.fields['address'].initial = dict['address']
        dict['form'] = form

        dict['all_orders'] = get_orders_of_this_user(dict['id'])
        print(dict['all_orders'])

        return render(request, 'home/user_profile.html', dict)
    else:
        form = LoginForm()
        return render(request, 'home/index.html', {'form': form})



def admin_login(request):
    if request.method == "POST":
        form = LoginForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            if is_admin(username, password):
                all_customers = all_users()
                dict = get_current_customer(all_customers, username)
                print("Hi admin " + username)
                request.session['username'] = dict['NAME']
                request.session['id'] = dict['ID']
                request.session['mobile'] = dict['PHONE NUMBER']
                request.session['email'] = dict['EMAIL']
                request.session['address'] = dict['ADDRESS']
                #request.session['password'] = dict['PASSWORD']
                request.session['account_type'] = dict['TYPES']
                request.session['login_message'] = "Login Successful! Welcome, "+dict['NAME']
                return redirect('/admindashboard/')
            else:
                form = LoginForm()
                dict = {}
                dict['login_message'] = "Login Failed! Sorry"
                dict['form'] = form
                return render(request, 'home/admin_login.html', dict)
    else:
        request.session.flush()
        form = LoginForm()
        return render(request, 'home/admin_login.html', {'form': form})

def admin(request):
    dict = {}
    dict['username'] = request.session.get('username')
    dict['id'] = request.session.get('id')
    dict['mobile'] = request.session.get('mobile')
    dict['email'] = request.session.get('email')
    dict['address'] = request.session.get('address')
    dict['account_type'] = request.session.get('account_type')
    dict['password'] = request.session.get('password')
    dict['cart_size'] = get_book_cart_len(dict['id'], 1) + get_electronics_cart_len(dict['id'], 1)
    dict['wishlist_size'] = get_book_wishlist_len(dict['id']) + get_electronics_wishlist_len(dict['id'])

    x,y =  get_comment_rating_cnts()
    dict['no_of_comment'] = x
    dict['no_of_rating']  = y
    x , y = total_sale()
    dict['total_sale'] = x + y
    dict['book_sale'] = x

Rokomari/templates/home/add_author.html
{% extends "home/home.html" %}
{% load static %}

    {% block sliding_block %}
    {% endblock %}


    {% block body_block%}

    <link rel="stylesheet" href="{% static "books/css/style.css" %}">
        <div class="featured-product product">
            <div class="container-fluid">
                <div class="section-header">
                    <h1>ADD New Author</h1>
                </div>
            </div>
        </div>
        <div class="login">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="login-form">
                            <div class="row">
								<form method="post" novalidate>
								  {% csrf_token %}

									{{ form.as_p }}

								  <button class="btn" type="submit">ADD</button>
								</form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="featured-product product">
            <div class="container-fluid">
                <div class="section-header">
                    <h5><a href={% url 'home:admin' %}> Return to Admin Dashboard </a> </h5>
                </div>
            </div>
        </div>
    {% endblock %}

    {% block best_seller  %}

    {% endblock %}

Rokomari/templates/home/add_book.html
{% extends "home/home.html" %}
{% load static %}

    {% block sliding_block %}
    {% endblock %}


    {% block body_block%}

    <link rel="stylesheet" href="{% static "books/css/style.css" %}">
        <div class="featured-product product">
            <div class="container-fluid">
                <div class="section-header">
                    <h1>ADD New Book</h1>
                </div>
            </div>
        </div>
        <div class="login">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="login-form">
                            <div class="row">
								<form method="post" novalidate>
								  {% csrf_token %}

									{{ form.as_p }}

								  <button class="btn" type="submit">ADD</button>
								</form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="featured-product product">
            <div class="container-fluid">
                <div class="section-header">
                    <h5><a href={% url 'home:admin' %}> Return to Admin Dashboard </a> </h5>
                </div>
            </div>
        </div>
    {% endblock %}

    {% block best_seller  %}

    {% endblock %}

Rokomari/templates/home/add_brand.html
{% extends "home/home.html" %}
{% load static %}

    {% block sliding_block %}
    {% endblock %}


    {% block body_block%}

    <link rel="stylesheet" href="{% static "books/css/style.css" %}">
        <div class="featured-product product">
            <div class="container-fluid">
                <div class="section-header">
                    <h1>ADD BRAND PAGE</h1>
                </div>
            </div>
        </div>
        <div class="login">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="login-form">
                            <div class="row">
								<form method="post" novalidate>
								  {% csrf_token %}

									{{ form.as_p }}

								  <button class="btn" type="submit">ADD</button>
								</form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="featured-product product">
            <div class="container-fluid">
                <div class="section-header">
                    <h5><a href={% url 'home:admin' %}> Return to Admin Page </a> </h5>
                </div>
            </div>
        </div>
    {% endblock %}

    {% block best_seller  %}

    {% endblock %}

Rokomari/templates/home/add_electronics.html
{% extends "home/home.html" %}
{% load static %}

    {% block sliding_block %}
    {% endblock %}


    {% block body_block%}

    <link rel="stylesheet" href="{% static "books/css/style.css" %}">
        <div class="featured-product product">
            <div class="container-fluid">
                <div class="section-header">
                    <h1>ADD ELECTRONICS PAGE</h1>
                </div>
            </div>
        </div>
        <div class="login">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="login-form">
                            <div class="row">
								<form method="post" novalidate>
								  {% csrf_token %}

									{{ form.as_p }}

								  <button class="btn" type="submit">ADD</button>
								</form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="featured-product product">
            <div class="container-fluid">
                <div class="section-header">
                    <h5><a href={% url 'home:admin' %}> Return to Admin Page </a> </h5>
                </div>
            </div>
        </div>
    {% endblock %}

    {% block best_seller  %}

    {% endblock %}

Rokomari/templates/home/add_electronics_category.html
{% extends "home/home.html" %}
{% load static %}

    {% block sliding_block %}
    {% endblock %}


    {% block body_block%}

    <link rel="stylesheet" href="{% static "books/css/style.css" %}">
        <div class="featured-product product">
            <div class="container-fluid">
                <div class="section-header">
                    <h1>ADD ELECTRONICS CATEGORY PAGE</h1>
                </div>
            </div>
        </div>
        <div class="login">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="login-form">
                            <div class="row">
								<form method="post" novalidate>
								  {% csrf_token %}

									{{ form.as_p }}

								  <button class="btn" type="submit">ADD</button>
								</form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="featured-product product">
            <div class="container-fluid">
                <div class="section-header">
                    <h5><a href={% url 'home:admin' %}> Return to Admin Page </a> </h5>
                </div>
            </div>
        </div>
    {% endblock %}

    {% block best_seller  %}

    {% endblock %}

Rokomari/templates/home/add_publisher.html
{% extends "home/home.html" %}
{% load static %}

    {% block sliding_block %}
    {% endblock %}


    {% block body_block%}

    <link rel="stylesheet" href="{% static "books/css/style.css" %}">
        <div class="featured-product product">
            <div class="container-fluid">
                <div class="section-header">
                    <h1>ADD ELECTRONICS PAGE</h1>
                </div>
            </div>
        </div>
        <div class="login">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="login-form">
                            <div class="row">
								<form method="post" novalidate>
								  {% csrf_token %}

									{{ form.as_p }}

								  <button class="btn" type="submit">ADD</button>
								</form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="featured-product product">
            <div class="container-fluid">
                <div class="section-header">
                    <h5><a href={% url 'home:admin' %}> Return to Admin Page </a> </h5>
                </div>
            </div>
        </div>
    {% endblock %}

    {% block best_seller  %}

    {% endblock %}

Rokomari/templates/home/all_electronics.html
{% extends "home/admin.html" %}
{% load static %}

    {% block actual_body %}
    {% endblock %}


    {% block body_block %}
		<div class="product-view">
            <div class="container-fluid">
                <div class="row"> 
					<div class="col-lg-9">
                        <div class="row">
						{% if electronics %}
							{% for item in electronics %}
								<div class="col-lg-3">
                        <div class="product-item">
                            <div class="product-title">
                                <a href="#">{{ item.TITLE }}</a>
								
                                <div class="ratting">
                                   {% for i in item.star_list %}
                                           <i class="fa fa-star"></i>
                                   {% endfor %}
                                </div>
                            </div>
                            <div class="product-image">                              
                                  <img src="{{ item.IMAGE_SRC }}" alt="Product Image">                                                   
                            </div>
                            <div class="product-price">
                                <h3><span>Price : </span>{{ item.PRICE }}</h3>															
                                <a class="btn" href={% url 'home:electronics:electronics_details' item.ID %}><i></i>Details</a>
                            </div>
                        </div>
                    </div>
							{% endfor %}
						{% endif %}                  
                </div>
            </div>
        </div>
		
    {% endblock %}

    {% block best_seller  %}

    {% endblock %}

Rokomari/templates/home/all_orders.html
{% extends "home/admin.html" %}
{% load static %}

    {% block actual_body %}
    {% endblock %}


    {% block body_block %}
		<div class="product-view">
            <div class="container-fluid">
                <div class="row"> 
					<div class="col-lg-11">
                        <div class="row">
							
                                <div class="table-responsive">
                                    <table class="table table-bordered">
                                        <thead class="thead-dark">
                                            <tr>
                                                
                                                <th>Order ID</th>
												<th>Products</th>
                                                <th>Date</th>
                                                <th>Total Price</th>
                                                <th>Status</th>
												<th>Is Delivered</th>
                                            </tr>
                                        </thead>
                                        <tbody>
											{% for od in all_orders %}
                                            <tr>
                                                
                                                <td>{{od.order_id}}</td>
												<td style="text-align: center; vertical-align: middle">
													{% for i in od.product %}
													{{ i.1 }} <br>
													{% endfor %}
                                                <td>{{od.time}}</td>
                                                <td>{{od.total_price}}</td>
                                                <td>{{od.status}}</td>
												<td style="text-align: center; vertical-align: middle">
												{% if not od.status == 'Delivered' %}
													<form method="POST">{% csrf_token %}																									  
													  <input type="hidden"  name="kotono" value="{{forloop.counter}}">
													  <input type="submit" class="fadeIn fourth" value="Delivered">
                                                    </form>
												{% endif %}
												</td>
                                            </tr>
											{% endfor %}
                                            
                                        </tbody>
                                    </table>
                                </div>
                            
						</div>
					</div>
				</div>
            </div>
        </div>
		
		
    {% endblock %}

    {% block best_seller  %}

    {% endblock %}

Rokomari/templates/home/update_electronics.html
{% extends "home/home.html" %}
{% load static %}

    {% block sliding_block %}
    {% endblock %}


    {% block body_block%}

    <link rel="stylesheet" href="{% static "books/css/style.css" %}">
        <div class="featured-product product">
            <div class="container-fluid">
                <div class="section-header">
                    <h1>UPDATE ELECTRONICS PAGE</h1>
                </div>
            </div>
        </div>
        <div class="login">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-6">
                        <div class="login-form">
                            <div class="row">
								<form method="post" novalidate>
								  {% csrf_token %}

									{{ form.as_p }}

								  <button class="btn" type="submit">Update</button>
								</form>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <div class="featured-product product">
            <div class="container-fluid">
                <div class="section-header">
                    <h5><a href={% url 'home:admin' %}> Return to Admin Page </a> </h5>
                </div>
            </div>
        </div>
    {% endblock %}

    {% block best_seller  %}

    {% endblock %}